# Generated by Django 2.2.6 on 2019-11-18 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aqua-store', '0002_agua_categoriaaguas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agua',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='aguas', to='aqua-store.CategoriaAguas'),
        ),
        migrations.AlterModelTable(
            name='produto',
            table='aqua-store',
        ),
    ]
